name: PUB WITH BUN
run-name: PUB triggered by ${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: "canary"
    - name: Install dependencies
      run: |
        bun install -f

    - name: Build project
      run: |
        bun run web:build
        
    - name: Deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_ADDR: ${{ secrets.SSH_ADDR }}
      run: |
        eval "$(ssh-agent -s)"
        mkdir -p ~/.ssh
        ssh-agent -s > ~/.ssh/ssh-agent.env
        . ~/.ssh/ssh-agent.env
        echo "$SSH_KEY" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        ssh-add /tmp/ssh_key
        ssh-keyscan -H "$SSH_ADDR" >> ~/.ssh/known_hosts
        ssh-add -l
        scp -i /tmp/ssh_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no ./build/* "$SSH_USER@SSH_ADDR":/www/cainb
        ssh -i /tmp/ssh_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no "$SSH_USER@$SSH_ADDR" /bin/bash << 'EOF'
          SERVICE="web"
          if systemctl is-active --quiet "$SERVICE"; then
            sudo systemctl stop "$SERVICE"
          fi
          sudo systemctl start "$SERVICE"
          systemctl is-active --quiet "$SERVICE" || exit 1
        EOF

