name: PUB WITH BUN
run-name: PUB triggered by ${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun_version: "canary"
    - name: Setup SSH
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_ADDR: ${{ secrets.SSH_ADDR }}
      run: |
          eval "$(ssh-agent -s)"
          ssh-agent -s > ~/.ssh/ssh-agent.env
          . ~/.ssh/ssh-agent.env
          echo "$SSH_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh-add /tmp/ssh_key
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_ADDR" >> ~/.ssh/known_hosts
          ssh-add -l
            
    - name: Install dependencies
      run: |
        bun install -f

    - name: Build project
      run: |
        bun run web:build

    - name: Deploy to remote server
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_ADDR: ${{ secrets.SSH_ADDR }}
      run: |
         ssh -vvv -o StrictHostKeyChecking=no "$SSH_USER@$SSH_ADDR" "echo 'SSH Connection Successful'"
