name: PUB WITH BUN
run-name: PUB triggered by ${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "canary"
      - name: Install Dependencies
        run: bun i -f

      - name: Run Build Script
        run: bun run web:build
        
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
                
      - name: Deploy
        run: |
          scp ./build/* "${{ secrets.SSH_USER }}@${{ secrets.SSH_ADDR }}:/www/cainb"
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_ADDR }}" "systemctl restart web"
          shell: /usr/bin/bash -e {0}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

